version: '3.9'

services:
  db:
    container_name: db
    image: postgres:16.2
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
      - TMDB_BASE_URL=${TMDB_BASE_URL}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:80"
    env_file:
      - .env

volumes:
  db-data:
